#!/bin/sh
# Regenerate the OPENSMT_OBJECTS block in src/Makevars.in.
#
# The list comes from upstream's own CMakeLists.txt files, not from `find
# src/opensmt -name '*.cc'`. Those are not the same set, and the difference is
# not cosmetic: v2.9.2 ships tsolvers/bvsolver/ and logics/BVLogic.cc but
# comments both out of its build, and they do not compile (BVLogic is left an
# incomplete type). Compiling everything present therefore fails, and picking
# the exclusions by hand would have to be redone, from compiler errors, at
# every version bump. Reading the build files makes upstream's own answer to
# "which sources are part of this library?" survive the bump instead.
#
# What this deliberately does not do is interpret CMake. It walks
# add_subdirectory()/include() from src/opensmt/CMakeLists.txt, takes the .cc
# names each file mentions, and skips comment lines -- enough for a tree whose
# build files are flat lists of sources, and it fails loudly rather than
# silently when a name does not resolve to a file on disk.
#
# An explicit list rather than $(wildcard ...): wildcard is a GNU make
# extension and would force SystemRequirements: GNU make.
set -eu

here=$(cd "$(dirname "$0")/.." && pwd)
vendor="${here}/src/opensmt"
mk="${here}/src/Makevars.in"
begin='# >>> generated by tools/objects.sh -- do not edit by hand'
end='# <<< generated'

[ -d "${vendor}" ] || { echo "ERROR: ${vendor} missing; run tools/vendor.sh" >&2; exit 1; }
grep -Fqx "${begin}" "${mk}" || { echo "ERROR: begin marker not found in ${mk}" >&2; exit 1; }
grep -Fqx "${end}" "${mk}" || { echo "ERROR: end marker not found in ${mk}" >&2; exit 1; }

work=$(mktemp -d)
trap 'rm -rf "${work}"' EXIT
: > "${work}/sources"
: > "${work}/seen"
echo "." > "${work}/queue"

# Breadth-first over the directories upstream includes in the build. A
# subdirectory that was pruned at import (parallel/, bin/) simply has no
# CMakeLists.txt and drops out here, which is why pruning needs no second list.
while [ -s "${work}/queue" ]; do
  d=$(head -1 "${work}/queue")
  sed '1d' "${work}/queue" > "${work}/queue.next" && mv "${work}/queue.next" "${work}/queue"

  grep -Fqx "${d}" "${work}/seen" && continue
  echo "${d}" >> "${work}/seen"

  f="${vendor}/${d}/CMakeLists.txt"
  [ -f "${f}" ] || continue

  # .cc names mentioned on non-comment lines, recorded against this directory.
  # The class includes '/' because a source may sit in a subdirectory of the
  # one declaring it ("${CMAKE_CURRENT_LIST_DIR}/polynomials/Translations.cc");
  # '}' is not in the class, so the match starts after the CMake variable and
  # only its leading slash needs removing.
  awk -v d="${d}" '
    /^[ \t]*#/ { next }
    {
      s = $0
      while (match(s, /[A-Za-z0-9_.\/+-]+\.cc/)) {
        name = substr(s, RSTART, RLENGTH)
        sub(/^\//, "", name)
        print (d == "." ? name : d "/" name)
        s = substr(s, RSTART + RLENGTH)
      }
    }' "${f}" >> "${work}/sources"

  # Directories this one pulls in, by add_subdirectory(x) or include(x/CMakeLists.txt).
  awk -v d="${d}" '
    /^[ \t]*#/ { next }
    {
      s = $0
      while (match(s, /add_subdirectory\([ \t]*[A-Za-z0-9_.-]+[ \t]*\)/)) {
        inner = substr(s, RSTART, RLENGTH)
        gsub(/add_subdirectory\([ \t]*|[ \t]*\)/, "", inner)
        print (d == "." ? inner : d "/" inner)
        s = substr(s, RSTART + RLENGTH)
      }
      s = $0
      while (match(s, /include\([ \t]*[A-Za-z0-9_.\/-]+CMakeLists\.txt[ \t]*\)/)) {
        inner = substr(s, RSTART, RLENGTH)
        gsub(/include\([ \t]*|[ \t]*\)|\/CMakeLists\.txt/, "", inner)
        print (d == "." ? inner : d "/" inner)
        s = substr(s, RSTART + RLENGTH)
      }
    }' "${f}" >> "${work}/queue"
done

# The generated parser. Upstream names these through CMake variables
# (${BISON_smt2newParser_OUTPUTS}), so no .cc name appears in the build file
# to be picked up above; tools/vendor.sh generates them under this path.
for gen in parsers/smt2new/smt2newparser.cc parsers/smt2new/smt2newlexer.cc; do
  echo "${gen}" >> "${work}/sources"
done

LC_ALL=C sort -u "${work}/sources" > "${work}/objects"

# Every name must resolve, or the list is wrong in a way that would surface as
# a confusing link error much later.
missing=0
while IFS= read -r src; do
  [ -f "${vendor}/${src}" ] || { echo "ERROR: listed but not present: src/opensmt/${src}" >&2; missing=1; }
done < "${work}/objects"
[ "${missing}" -eq 0 ] || exit 1

tmp="${work}/Makevars.in"
awk -v b="${begin}" '$0 == b { exit } { print }' "${mk}" > "${tmp}"
{
  echo "${begin}"
  echo "OPENSMT_OBJECTS = \\"
  sed 's|^|\topensmt/|; s|\.cc$|.o \\|' "${work}/objects" | sed '$ s/ \\$//'
  echo "${end}"
} >> "${tmp}"
awk -v e="${end}" 'found { print } $0 == e { found = 1 }' "${mk}" >> "${tmp}"
cat "${tmp}" > "${mk}"

built=$(wc -l < "${work}/objects" | tr -d ' ')
present=$(cd "${vendor}" && find . -name '*.cc' -type f | wc -l | tr -d ' ')
echo "objects.sh: ${built} sources built, of ${present} present in the tree"
if [ "${built}" -ne "${present}" ]; then
  echo "objects.sh: not built by upstream (expected -- e.g. the disabled bitvector solver):"
  (cd "${vendor}" && find . -name '*.cc' -type f | sed 's|^\./||' | LC_ALL=C sort) > "${work}/present"
  LC_ALL=C comm -13 "${work}/objects" "${work}/present" | sed 's|^|  |'
fi
